server:
  port: 8004
spring:
  application:
    name: apply-credit-card-service
  datasource:
    url: jdbc:mysql://${MSQL_HOSTNAME:localhost}:${MSQL_PORT:3306}/${MSQL_DB_NAME:cc_application}
    username: ${MSQL_USERNAME:root}
    password: ${MSQL_PASSWORD:root}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
    generate-ddl: true
    show-sql: false
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_BROKER_HOST:localhost}
          defaultBrokerPort: ${KAFKA_BROKER_PORT:9092}
          auto-create-topics: true
      function:
        definition: publishNewCreditCardEvent
      bindings:
        publishNewCreditCardEvent-out-0:
          destination: CreditCardApplication
          group: creditcard
