server:
  port: 8004
spring:
  application:
    name: apply-credit-card-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cc_application
    username: root
    password: root
  jpa:
    generate-ddl: true
    show-sql: false
  cloud:
    stream:
      function:
        definition: publishNewCreditCardEvent
      bindings:
        publishNewCreditCardEvent-out-0:
          destination: CreditCardApplication
          group: creditcard